theme = "catppuccin_macchiato"

[editor]
auto-save = true
auto-format = true
line-number = "relative"
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name", "diagnostics"]
right = ["selections", "position"]

[keys.normal]
tab = ":buffer-next"
S-tab = ":buffer-previous"
