[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.vale]
command = "vale-ls"
args = []
config = {}

[language-server.nixd]
command = "nixd"
args = []
config = {}

[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
rulers = [89]
language-servers = [
  # { name = "pyright", except-features = ["diagnostics"] },
  { name = "pyright", except-features = [] },
  # { name = "vale", except-features = [] },
]

[[language]]
name = "toml"
scope = "source.toml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[language]]
name = "markdown"
scope = "source.md"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-servers = [
  { name = "vale", except-features = [] },
]

[[language]]
name = "json"
scope = "source.json"
auto-format = false
formatter = { command = "dprint", args = ["fmt", "--stdin", "json"] }

[[language]]
name = "yaml"
scope = "source.yaml"
auto-format = false
formatter = { command = "dprint", args = ["fmt", "--stdin", "yaml"] }
language-servers = ["craft-ls"]

[language-server.craft-ls]
command = "craft-ls"

[[language]]
name = "nix"
scope = "source.nix"
formatter = { command = "alejandra", args = ["--quiet", "-"] }
auto-format = true
language-servers = [
  { name = "nixd", except-features = [] },
]
