[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.vale]
command = "vale-ls"
args = []
config = {}

[language-server.nixd]
command = "nixd"
args = []
config = {}

[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true
rulers = [89]
language-servers = [
  # { name = "pyright", except-features = ["diagnostics"] },
  { name = "pyright", except-features = [] },
  # { name = "vale", except-features = [] },
]

[[language]]
name = "toml"
scope = "source.toml"
formatter = { command = "dprint", args = ["fmt", "--stdin", "toml"] }

[[language]]
name = "markdown"
scope = "source.md"
formatter = { command = "dprint", args = ["fmt", "--stdin", "md"] }
language-servers = [
  { name = "vale", except-features = [] },
]

[[language]]
name = "javascript"
scope = "source.js"
formatter = { command = "dprint", args = ["fmt", "--stdin", "js"] }

[[language]]
name = "nix"
scope = "source.nix"
formatter = { command = "alejandra", args = ["--quiet", "-"] }
auto-format = true
language-servers = [
  { name = "nixd", except-features = [] },
]
