#cloud-config
package_upgrade: true
snap:
  commands:
    0: snap install microceph
    1: sudo microceph cluster bootstrap
    2: sudo microceph disk add loop,1G,3
    3: sudo microceph enable rgw
    4: sudo microceph.radosgw-admin user create --uid test --display-name test --access-key=foo --secret-key=bar
